Atualizando a lista de membros e egressos.
pet-informatica/pet-informatica.github.io pull request #3
Opened 2020-04-07 00:16 UTC by alpvj

2020-04-07 00:29 UTC, hcaula approved these changes

2020-04-07 00:29 UTC, hcaula commented on package.json
> +    "natives": "^1.1.6",
Pq esse package novo?

2020-04-07 00:34 UTC, MarconiGRF commented on package.json
> +    "natives": "^1.1.6",
Devido a um erro causado pela versão deprecada do gulp-nodemon. O uso desse pacote é a solucão.

Mais infos aqui: https://github.com/nodejs/node/issues/25132

2020-04-07 00:35 UTC, MarconiGRF commented on .gitignore
> +npm-shrinkwrap.json
Ignorando esse arquivo para resolver um problema de npm install com versões muito antigas do nodejs e gulp.

2020-04-07 00:35 UTC, MarconiGRF approved these changes

2020-04-07 00:48 UTC, peaonunes commented
Uma possível melhoria seria mover todos os dados estáticos para um arquivo `members-data.js`. Poderia-se definir dois arrays de objetos: `members` e `graduates` . Cada item no array é o objeto de um membro com `nome`, `desc`, `pic` e `face.

Já no código em `members.js` o trabalho seria apenas fazer um `map` em cada array e retornar o componente `Member` pra cada entrada com as respectivas `props`. 
Enxugaria bastante o código.

2020-04-07 04:35 UTC, alpvj commented
> Uma possível melhoria seria mover todos os dados estáticos para um arquivo `members-data.js`. Poderia-se definir dois arrays de objetos: `members` e `graduates` . Cada item no array é o objeto de um membro com `nome`, `desc`, `pic` e `face.
> 
> Já no código em `members.js` o trabalho seria apenas fazer um `map` em cada array e retornar o componente `Member` pra cada entrada com as respectivas `props`.
> Enxugaria bastante o código.

2020-04-07 04:39 UTC, alpvj commented
> Uma possível melhoria seria mover todos os dados estáticos para um arquivo `members-data.js`. Poderia-se definir dois arrays de objetos: `members` e `graduates` . Cada item no array é o objeto de um membro com `nome`, `desc`, `pic` e `face.
> 
> Já no código em `members.js` o trabalho seria apenas fazer um `map` em cada array e retornar o componente `Member` pra cada entrada com as respectivas `props`.
> Enxugaria bastante o código.

Eu implementei minha interpretação disso mas não tô conseguindo de jeito nenhum usar export/import pra poder por o array na file members-data.js.

2020-04-07 04:45 UTC, alpvj commented
O que eu queria fazer era uma função na file de members-data.js:
returnMembers(bool active){
    arr = [];
    for (auto m : MembersArray)
        if (m.graduate == active) arr.push(m);
    return arr;
}
Daí usuaria:
parameters = data.returnMembers(true/false);

Mas, mais uma vez, não tô conseguindo usar export/import por algum motivo(?).

2020-04-07 14:40 UTC, hcaula requested changes
@alpvj Aqui o que tu deve fazer.
1. Em um arquivo separado, mas no mesmo diretório, cria o arquivo `membersData.js` (pode ser em outro diretório, mas por simplicidade, pode deixar no mesmo). Nota que, antes das variáveis, tem esse `export const`. Isso significa que a gente vai poder importar, em outro arquivo, a varíavel em específico. Isso vai ser útil pra diferenciar o array de membros e ex-membros.
```javascript
// membersData.js
export const members = [
   {
    name: "Aline Gouveia",
    desc: "amtg",
    pic: "imagem da aline",
    face: "face da aline"
  },
  {
    name: "André Vansconcelos",
    desc: "alpvj",
    pic: "imagem da andré",
    face: "face do andré"
  },
  ...
]

export const graduates = [
  {
    name: "Henrique Caúla",
    desc: "lhtc",
    pic: "imagem do tatinho",
    face: "face do tatinho"
  },
  {
    name: "Divino Neto",
    desc: "dgmn",
    pic: "imagem divina",
    face: "face divina"
  },
  ...
]
```
2. Em `member.js`, tu importa essas variáveis e itera sobre elas, como tu tava fazendo.
```javascript
// member.js
import { members, graduates } from './membersData'

var Members = React.createClass({
  render: function(){
     {members.map(member => {
       <Member name={member.name} desc={member.desc} pic={member.pic} face={member.image} />
     })}
  }
})

var ExNembers = React.createClass({
  render: function(){
     {graduates.map(member => {
       <Member name={member.name} desc={member.desc} pic={member.pic} face={member.image} />
     })}
  }
})
```

2020-04-07 23:13 UTC, peaonunes commented
O que Tato citou deve resolver o problema em exportar as variáveis. 
Uma única coisa que ficou faltando é passar `key` para o componente dentro do map.
```jsx
var Members = React.createClass({
  render: function(){
     {members.map(member => {
       <Member key={member.desc} name={member.name} desc={member.desc} pic={member.pic} face={member.image} />
     })}
  }
})
```
Keys são propriedades que identificam unicamente um elemento quando ele é criado como uma lista de elementos (que é o caso). Isso ajuda o React a identificar remoções, adições, etc. É uma boa prática sempre colocar mesmo que nada vá mudar quando o cara estiver no site. [React Lists and Keys](https://reactjs.org/docs/lists-and-keys.html#keys)

2020-04-08 18:40 UTC, gabrielnogueiralt approved these changes

2020-04-08 18:48 UTC, JBezerra approved these changes
Acredito que com os pontos já levantados e alterados, o site ficou no jeito 😛

2020-04-09 18:03 UTC, alpvj commented
> @alpvj Aqui o que tu deve fazer.
> 
> 1. Em um arquivo separado, mas no mesmo diretório, cria o arquivo `membersData.js` (pode ser em outro diretório, mas por simplicidade, pode deixar no mesmo). Nota que, antes das variáveis, tem esse `export const`. Isso significa que a gente vai poder importar, em outro arquivo, a varíavel em específico. Isso vai ser útil pra diferenciar o array de membros e ex-membros.
> 
> ```js
> // membersData.js
> export const members = [
>    {
>     name: "Aline Gouveia",
>     desc: "amtg",
>     pic: "imagem da aline",
>     face: "face da aline"
>   },
>   {
>     name: "André Vansconcelos",
>     desc: "alpvj",
>     pic: "imagem da andré",
>     face: "face do andré"
>   },
>   ...
> ]
> 
> export const graduates = [
>   {
>     name: "Henrique Caúla",
>     desc: "lhtc",
>     pic: "imagem do tatinho",
>     face: "face do tatinho"
>   },
>   {
>     name: "Divino Neto",
>     desc: "dgmn",
>     pic: "imagem divina",
>     face: "face divina"
>   },
>   ...
> ]
> ```
> 
> 1. Em `member.js`, tu importa essas variáveis e itera sobre elas, como tu tava fazendo.
> 
> ```js
> // member.js
> import { members, graduates } from './membersData'
> 
> var Members = React.createClass({
>   render: function(){
>      {members.map(member => {
>        <Member name={member.name} desc={member.desc} pic={member.pic} face={member.image} />
>      })}
>   }
> })
> 
> var ExNembers = React.createClass({
>   render: function(){
>      {graduates.map(member => {
>        <Member name={member.name} desc={member.desc} pic={member.pic} face={member.image} />
>      })}
>   }
> })
> ```

Eu tentei fazer isso antes mas tem algum erro que não consegui descobrir. Talvez seja a versão que não aceita exports assim. Já tentei module.exports export default e nem lembro oque mais.
![Screen Shot 2020-04-09 at 2 59 35 PM](https://user-images.githubusercontent.com/42820943/78926266-2d6a7280-7a73-11ea-881f-d9eebfd08f3b.png)

2020-04-23 14:08 UTC, hcaula approved these changes
@alpvj Entendi... que estranho... A versão do node deve estar bem desatualizada então. Pode deixar assim, então (o site precisa de um remake mesmo eventualmente kkk).

2020-04-23 21:58 UTC, MarconiGRF approved these changes

2020-04-23 21:58 UTC, merged